### ISSUE TITLE
Syntax checker/ F2003 parser issues

### ISSUE THREAD

**Issue by amsi7193** [NCAR-CISL-ASAP/KGen#1]
Submitted by John Dennis. Run on CESM.

\

Reading(115/174):  /glade/u/home/dennis/cesm1_3_beta15/models/ocn/pop2/source/tavg.F90
WARNING: While processing 'string-1008733952' (mode='free')..
  837:!-----------------------------------------------------------------------
  838:
  839:  	write(char_temp,1100) 'tavg',ns ;  1100 format (a,i1) <== no parse pattern found for "1100 format (F2PY_EXPR_TUPLE_255205)" in 'Do' block.

/glade/u/home/dennis/cesm1_3_beta15/models/ocn/pop2/drivers/cpl/ocn_import_export.F90
Near line # 361:
1100  FORMAT ('comm_diag ', a3, 1x, a4, 1x, a8, 1x, es26.19:, 1x, a6)

/glade/u/home/dennis/cesm1_3_beta15/models/atm/cam/src/dynamics/fv/geopk.F90
Near line # 259:
POINTER (ptr_inbuf8, inbuf8)

Reading(68/116):  /glade/u/home/dennis/cesm1_3_beta15/models/atm/cam/src/physics/cam/convect_shallow.F90
ERROR: While processing 'string-581782560' (mode='free')..
  314:
  315: 	tke_idx = pbuf_get_index('tke')
  316:
  317:  case('UNICON') ! Sungsu Park's General Convection Model <== following character continuation: "'", expected None.

Reading(33/74):  /glade/u/home/dennis/cesm1_3_beta15/models/ice/cice/src/source/ice_probability.F90
WARNING: Following statement is not correctly parsed
  	erfc = ((((((((((((((((((((((p22 * u + p21) * u + p20)                                      	* u + p19) * u + p18)                                      	* u + p17) * u + p16)                                      	* u + p15) * u + p14)                                      	* u + p13) * u + p12)                                      	* u + p11) * u + p10)                                      	* u + p09) * u + p08)                                      	* u + p07) * u + p06)                                      	* u + p05) * u + p04)                                      	* u + p03) * u + p02)                                      	* u + p01) * u + p00) * t * exp(-x**2)

**Comment by grnydawn** [comment]
This issue is closed by having commits of:
- 72324d8fdb250e51874b392a908edf5502d958f6
- 9d32d6d541881dd5176cb6a8d2b162ed9564febd
- 5427c5f0e24fd58c42ae45d036da1422df6257d2

**Comment by grnydawn** [comment]
This issue was closed by 
72324d8
9d32d6d
5427c5f
