### ISSUE TITLE
support for name resolution by implicit rules

### ISSUE THREAD

**Issue by grnydawn** [NCAR-CISL-ASAP/KGen#109]

**Comment by amsi7193** [comment]
Added partial support for implicit rules. Now, if implicit statements are used in the program, or passed as input arguments, they will be written into the output files generated by kgen during state data collection. However, output variables will still not be recognized as such, and will still not be verified. This pertains to how KGen handles output variables and requires a more long-term solution. All updates have been pushed to branch issue-109. This branch is ready to merge to devel.

**Comment by grnydawn** [comment]
This issue is resolved by v0.6.1
