### ISSUE TITLE
Current development branch of KGEN generates invalid fortran code

### ISSUE THREAD

**Issue by johnmauff** [NCAR-CISL-ASAP/KGen#114]
I recently switched KGEN to the most recent development branch and it started generating invalid Fortran code.   This bug appears to be related to the presence of comment lines in the subroutine declaration block.  The resulting block is seen below:

       SUBROUTINE advance_clubb_core(dt, wm_zt, wp2, up2, vp2, um_forcing, vm_forcing, edsclrm_forcing, rho_ds_zm, &
        invrs_rho_ds_zt, fcor, l_implemented, um, vm, edsclrm, upwp, vpwp, err_code, kgen_unit, total_time)
                USE kgen_utils_mod, ONLY : kgen_dp, check_t, kgen_init_check, kgen_print_check, kgen_perturb
             ( l_implemented, dt, fcor, sfc_elevation, hydromet_dim, & ! intent(in)
               thlm_forcing, rtm_forcing, um_forcing, vm_forcing, & ! intent(in)
               sclrm_forcing, edsclrm_forcing, wprtp_forcing, &     ! intent(in)
               wpthlp_forcing, rtp2_forcing, thlp2_forcing, &       ! intent(in)
               rtpthlp_forcing, wm_zm, wm_zt, &                     ! intent(in)
               wpthlp_sfc, wprtp_sfc, upwp_sfc, vpwp_sfc, &         ! intent(in)
               wpsclrp_sfc, wpedsclrp_sfc, &                        ! intent(in)
               p_in_Pa, rho_zm, rho, exner, &                       ! intent(in)
               rho_ds_zm, rho_ds_zt, invrs_rho_ds_zm, &             ! intent(in)
               invrs_rho_ds_zt, thv_ds_zm, thv_ds_zt, hydromet, &   ! intent(in)
               rfrzm, radf, do_expldiff, &                          ! intent(in)
               wphydrometp, wp2hmp, rtphmp_zt, thlphmp_zt, &        ! intent(in)
               host_dx, host_dy, &                                  ! intent(in) 
               um, vm, upwp, vpwp, up2, vp2, &                      ! intent(inout)
               thlm, rtm, wprtp, wpthlp, &                          ! intent(inout)
               wp2, wp3, rtp2, thlp2, rtpthlp, &                    ! intent(inout)
               sclrp2, sclrprtp, sclrpthlp, &                       ! intent(inout)
               wpsclrp, edsclrm, err_code, &                        ! intent(inout)
               rcm, wprcp, cloud_frac, ice_supersat_frac, &         ! intent(out)
               rcm_in_layer, cloud_cover, &                         ! intent(out)
               khzm, khzt, &                                        ! intent(out)
               qclvar, thlprcp_out, &                                            ! intent(out)
               pdf_params )                                         ! intent(out)

**Comment by johnmauff** [comment]
The Makefile necessary to reproduce this bug is located in the directory yellowstone:/glade/p/work/dennis/generate-kernels/advance_windm_edsclrm_new

**Comment by grnydawn** [comment]
This issue is resolved with v0.6.1
