### ISSUE TITLE
Failure to check output variables that are not passed through the call-site

### ISSUE THREAD

**Issue by johnmauff** [NCAR-CISL-ASAP/KGen#115]
KGEN is not currently check the state of variables that are not passed through the call-site.  Consider extracting a kernel at the following call-site 

     call Euler()

  The subroutine Euler() modifies the values of a user defined data-type Trunoff which is used within the subroutine Euler.  Because Trunoff is not passed through the subroutine interface, it is never checked for correctness.

**Comment by grnydawn** [comment]
This issue is resolved with v0.6.1
