### ISSUE TITLE
kgen_write issue with pio

### ISSUE THREAD

**Issue by rashmi25** [NCAR-CISL-ASAP/KGen#116]
kgen fails to bypass pio when it should and to use pio_types instead.
[kgen_output.txt](https://github.com/NCAR-CISL-ASAP/KGen/files/24536/kgen_output.txt)

![screen shot 2015-10-30 at 12 41 44 pm](https://cloud.githubusercontent.com/assets/12300681/10856205/b902c292-7f0b-11e5-82b8-74928df7a80a.png)

**Comment by grnydawn** [comment]
This issue is supposed to be resolved with v0.6.1 To work, user needs to use exclude.ini with proper exclusion information such as "skip_module" action explained in User's guide. Even though the fix for this issues is not tested, we will raise another issue on new NCAR github if requred.
