### ISSUE TITLE
indirect module import via multiple bridge modules

### ISSUE THREAD

**Issue by amsi7193** [NCAR-CISL-ASAP/KGen#20]
/// commented out
Complex data types are still not being correctly handled by Kgen. When a type is declared in a separate module and referenced from the calling subroutine as well as the kernel subroutine, Kgen fails to pick up on multiple levels of reference.
The problem only exists if the datatype is defined in a separate module file and used by the kernel.
/// commented out

When an identifier is imported from a module through multiple modules in-between, KGEN does not correctly generate Fortran USE statement to import the identifier.

**Comment by grnydawn** [comment]
This issue is resolved with v0.6.1
