### ISSUE TITLE
Inflexible Fortran version assumptions based on file suffix

### ISSUE THREAD

**Issue by johnmauff** [NCAR-CISL-ASAP/KGen#25]
KGEN, or f4py makes assumptions on the version of fortran based on the file suffix.  For example in in the MPAS model which uses Fortran 2003 syntax but whose files are named with *.F KGEN fails.  When the files are renamed to be *.F90 KGEN works.

**Comment by grnydawn** [comment]
This issue is addressed in branch issue-45

**Comment by grnydawn** [comment]
resolved by merging issue-45 branch to devel
