### ISSUE TITLE
Difficult to add unit tests that do not use *.F90 file suffix

### ISSUE THREAD

**Issue by johnmauff** [NCAR-CISL-ASAP/KGen#26]
When I attempted to add a new unit test I discovered that the use of *.F90 file suffix is hardware into the Makefile.  This makes creating a unit test that uses a *.F file suffix difficult.

**Comment by grnydawn** [comment]
This issue is address by branch issue-45

**Comment by grnydawn** [comment]
resolved by merging issue-45 branch to devel
