### ISSUE TITLE
Challenging to apply KGEN to MPAS

### ISSUE THREAD

**Issue by johnmauff** [NCAR-CISL-ASAP/KGen#45]
The MPAS model uses very deeply nested fortran data-structures.  This makes the extraction of kernels from MAS very challenging.  In particular an attempted extraction of a computational routine in MPAS requires the rebuilding of the PIO library.  An attempt to perform an extraction on MPAS can be found in the directory /glade/p/work/dennis/MPAS-kernel.  Typing 'make' will execute KGEN.

**Comment by grnydawn** [comment]
Two MPAS kernels are extracted with v0.6.1. There are still some issues with MPAS kernel extractions, but the issues will be handled by another issue.
