### ISSUE TITLE
KGEN failes to create a complete state file

### ISSUE THREAD

**Issue by johnmauff** [NCAR-CISL-ASAP/KGen#69]
KGEN creates an incomplete state file when generating a kernel from MPAS.  The working directory is on yellowstone:/glade/p/work/dennis/MPAS-kernel/   

While using the  Makefile in the MPAS-kernel to generate a MPAS kernel completes, the generated state file 'state/mpas_derived_types.F90' is incomplete.  Note that the last line in this file is an 'END IF'.  Additional code to complete the subroutine and the module is missing.

**Comment by grnydawn** [comment]
John,

I tried to reproduce your result but I could not see the incomplete file in
my "state" folder. Could you check if the file is generated together with
the other file?

Thanks,

Youngsung

**Comment by johnmauff** [comment]
Will check right now.

John

**Comment by johnmauff** [comment]
Youngsung,

  I think this must have been an older file that was left over from a
previous KGEN execution.  I will try and compile MPAS again with the
derived_type file excluded.

Thanks,
John

**Comment by grnydawn** [comment]
John,

I see. I am going to work on issues related MPAS support today too and let
me know if there is something I can fix quickly.

Thanks,

Youngsung

**Comment by johnmauff** [comment]
This issue is actually a user error.  I consider it closed
