### ISSUE TITLE
source code formatting is not preserved

### ISSUE THREAD

**Issue by johnmauff** [NCAR-CISL-ASAP/KGen#84]
When KGEN generates a kernel, the original source code formatting is not preserved.  This complicates the reintroduction of back into the original application.  An example is seen below 

Original:

  ! Size calculation functions.
  use micro_mg_utils, only: &
       size_dist_param_liq, &
       size_dist_param_basic, &
       avg_diameter

  ! Microphysical processes.
  use micro_mg_utils, only: &
       ice_deposition_sublimation, &
       kk2000_liq_autoconversion, &
       ice_autoconversion, &
       immersion_freezing, &
       contact_freezing, &
       snow_self_aggregation, &
       accrete_cloud_water_snow, &
       secondary_ice_production, &
       accrete_rain_snow, &
       heterogeneous_rain_freezing, &
       accrete_cloud_water_rain, &
       self_collection_rain, &
       accrete_cloud_ice_snow, &
       evaporate_sublimate_precip, &
       bergeron_process_snow

KGEN transformed code:

            ! Size calculation functions.
            USE micro_mg_utils, ONLY: size_dist_param_liq
            USE micro_mg_utils, ONLY: size_dist_param_basic
            USE micro_mg_utils, ONLY: avg_diameter
            ! Microphysical processes.
            USE micro_mg_utils, ONLY: kk2000_liq_autoconversion
            USE micro_mg_utils, ONLY: ice_autoconversion
            USE micro_mg_utils, ONLY: immersion_freezing
            USE micro_mg_utils, ONLY: contact_freezing
            USE micro_mg_utils, ONLY: snow_self_aggregation
            USE micro_mg_utils, ONLY: accrete_cloud_water_snow
            USE micro_mg_utils, ONLY: secondary_ice_production
            USE micro_mg_utils, ONLY: accrete_rain_snow
            USE micro_mg_utils, ONLY: heterogeneous_rain_freezing
            USE micro_mg_utils, ONLY: accrete_cloud_water_rain
            USE micro_mg_utils, ONLY: self_collection_rain
            USE micro_mg_utils, ONLY: accrete_cloud_ice_snow
            USE micro_mg_utils, ONLY: evaporate_sublimate_precip
            USE micro_mg_utils, ONLY: bergeron_process_snow
            USE micro_mg_utils, ONLY: ice_deposition_sublimation

  A makefile which reproduces this problem is in the directory: /glade/p/work/dennis/generate-kernels/MG2r

**Comment by grnydawn** [comment]
This issue is resolved with v0.6.1
