### ISSUE TITLE
Fortran specification of Specific_Binding is not supported yet

### ISSUE THREAD

**Issue by johnmauff** [NCAR-CISL-ASAP/KGen#88]
While attempting to extract a kernel from the new POP ecosys code I am getting a Fortran specification error.  Note that this bug can be reproduced by executing 'make' in the directory yellowstone:/glade/p/work/dennis/generate-kernels/init_passive_tracers  

The error is as follows:

Reading /glade/scratch/dennis/PFS.T62_g16.CECO.yellowstone_intel.151008-125937/bld/ocn/source/ecosys_restore_timescale_file.F90
WARNING: While processing 'string-84970496' (mode='free')..
   17:
   18:   contains
   19:     procedure, public :: init <== nothing analyzed
   20:     procedure, private :: read_namelist
   21:     procedure, private :: read_restoring_timescale_from_file
WARNING: While processing 'string-84970496' (mode='free')..
   18:   contains
   19:     procedure, public :: init
   20:     procedure, private :: read_namelist <== nothing analyzed
   21:     procedure, private :: read_restoring_timescale_from_file
   22:
WARNING: While processing 'string-84970496' (mode='free')..
   19:     procedure, public :: init
   20:     procedure, private :: read_namelist
   21:     procedure, private :: read_restoring_timescale_from_file <== nothing analyzed
   22:
   23:  end type ecosys_restore_timescale_file_type
	in the search of "ecosys_restore_timescale_file_type" directly from ecosys_restore.F90 and originally from ecosys_restore.F90

Error: Fortran specification of Specific_Binding is not supported yet.

'kgen.log' in output folder contains detail information of this error.
If you send the log file to 'kgen@ucar.edu', that could be very
helpful for us to support this Fortran spec. in future KGEN version.

**Comment by grnydawn** [comment]
The latest devel branch as of commit # e98ae637a4c56cbcc2b17d574a025cab7d3d3192 resolved this issue.
