### ISSUE TITLE
Masked_Elsewhere_Stmt not supported

### ISSUE THREAD

**Issue by johnmauff** [NCAR-CISL-ASAP/KGen#90]
A syntax check of newly added POP code has revealed that Masked_elsewhere_Stmt are not supported.  This error can be reproduced by running Kgen in syntax checking mode on the following file:

/glade/scratch/dennis/PFS.T62_g16.CECO.yellowstone_intel.151008-125937/bld/ocn/source/abio_dic_dic14_mod.F90

**Comment by grnydawn** [comment]
resolved by release version 0.5.3
